# -*- coding: utf-8 -*-
"""XGB App Recommendation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MwPf43HZaHsiST20i4tkGQ99y-fUGqCR
"""



"""Import Libraries"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.preprocessing import LabelEncoder
from sklearn.neighbors import NearestNeighbors
from xgboost import XGBRegressor

print(" All imports successful! Ready to build ")

df = pd.read_csv('/content/apps_data.csv')

df.head()

df.tail()

df.info()

"""Data Processing and Cleaning"""

print("=== Missing Values ===")
print(df.isnull().sum())

print("\n=== Data Types ===")
print(df.dtypes)

"""Cleaning Duplicates & Obvious Bad Rows"""

# Drop duplicate apps (keep first occurrence)
df.drop_duplicates(subset="App", keep="first", inplace=True)

# Drop rows where Rating is missing (it's our target variable)
df.dropna(subset=["Rating"], inplace=True)

# Remove junk row (a known bad row in this dataset)
df = df[df["Rating"] <= 5.0]

print(f"Clean shape: {df.shape}")

"""Cleaing Size"""

def clean_size(size):
    if pd.isnull(size) or size == "Varies with device":
        return np.nan
    elif "M" in str(size):
        return float(size.replace("M", ""))
    elif "k" in str(size):
        return float(size.replace("k", "")) / 1024  # convert to MB
    else:
        return np.nan

df["Size"] = df["Size"].apply(clean_size)
print("Size column cleaned")
print(df["Size"].describe())

"""Cleaning Installs & Price"""

# Clean Installs: remove '+' and ',' then convert to int
df["Installs"] = df["Installs"].str.replace("+", "", regex=False)\
                                .str.replace(",", "", regex=False)
df["Installs"] = pd.to_numeric(df["Installs"], errors="coerce")

# Clean Price: remove '$' and convert to float
df["Price"] = df["Price"].str.replace("$", "", regex=False)
df["Price"] = pd.to_numeric(df["Price"], errors="coerce")

print("Installs & Price cleaned")
print(df[["Installs", "Price"]].describe())

"""Ecoding Categorical Columns"""

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df["Category_encoded"] = le.fit_transform(df["Category"].astype(str))
df["Content_Rating_encoded"] = le.fit_transform(df["Content Rating"].astype(str))
df["Type_encoded"] = le.fit_transform(df["Type"].astype(str))  # Free vs Paid

print("Categorical columns encoded")
print(df[["Category", "Category_encoded"]].drop_duplicates().head(10))

"""Filling numeric nulls with median"""

# Fill numeric nulls with median
df["Size"] = df["Size"].fillna(df["Size"].median())
df["Installs"] = df["Installs"].fillna(df["Installs"].median())
df["Price"] = df["Price"].fillna(0)  # assume free if missing
df["Reviews"] = pd.to_numeric(df["Reviews"], errors="coerce")
df["Reviews"] = df["Reviews"].fillna(0)

print(" Missing values handled")
print(df.isnull().sum())

"""Selecting Features and Targets"""

# Features we'll use for prediction
features = [
    "Category_encoded",
    "Content_Rating_encoded",
    "Type_encoded",
    "Size",
    "Price",
    "Installs",
    "Reviews"
]

X = df[features]
y = df["Rating"]

print(f" Features shape: {X.shape}")
print(f" Target shape: {y.shape}")
print(f"\nFeature summary:")
X.describe()

"""Splitting into train and test sets"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print(f" Training set:   {X_train.shape}")
print(f" Testing set:    {X_test.shape}")

"""Training Random Forest Regressor"""

from sklearn.ensemble import RandomForestRegressor

rf_model = RandomForestRegressor(
    n_estimators=100,
    random_state=42,
    n_jobs=-1  # use all CPU cores
)

rf_model.fit(X_train, y_train)
print(" Random Forest trained!")

"""Train XGBoost"""

from xgboost import XGBRegressor

xgb_model = XGBRegressor(
    n_estimators=100,
    learning_rate=0.1,
    random_state=42,
    verbosity=0
)

xgb_model.fit(X_train, y_train)
print(" XGBoost trained!")

"""Testing Models"""

from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

# Predictions
rf_preds = rf_model.predict(X_test)
xgb_preds = xgb_model.predict(X_test)

# Metrics
def evaluate(name, y_true, y_pred):
    mae = mean_absolute_error(y_true, y_pred)
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    print(f" {name}")
    print(f"   MAE:  {mae:.4f}")
    print(f"   RMSE: {rmse:.4f}\n")

evaluate("Random Forest", y_test, rf_preds)
evaluate("XGBoost", y_test, xgb_preds)

"""Visualiszing Feature Importance of Random Forest"""

import matplotlib.pyplot as plt
import seaborn as sns

importance_df = pd.DataFrame({
    "Feature": features,
    "Importance": rf_model.feature_importances_
}).sort_values("Importance", ascending=False)

plt.figure(figsize=(8, 5))
sns.barplot(
    data=importance_df,
    x="Importance",
    y="Feature",
    hue="Feature",        # fix: assign hue
    palette="viridis",
    legend=False           # fix: hide redundant legend
)
plt.title("Feature Importance — Random Forest")
plt.tight_layout()
plt.show()

"""Moving to Streamlit"""

!pip install pyngrok -q
print(" pyngrok installed!")

"""Save trained models & scaler to disk"""

import pickle

# Save models and preprocessing objects
with open("xgb_model.pkl", "wb") as f:
    pickle.dump(xgb_model, f)

# The variables knn, scaler, and rec_matrix were not defined in previous steps.
# Removing lines that attempt to save them.

with open("df_clean.pkl", "wb") as f:
    pickle.dump(df, f)

print(" All models saved!")

app_code = '''
import streamlit as st
import pandas as pd
import numpy as np
import pickle

# ── Page config ──────────────────────────────────────────────
st.set_page_config(
    page_title="Mobile App Success Predictor",
    page_icon="",
    layout="centered"
)

# ── Load models & data ───────────────────────────────────────
@st.cache_resource
def load_assets():
    with open("xgb_model.pkl", "rb") as f:
        model = pickle.load(f)
    with open("knn_model.pkl", "rb") as f:
        knn = pickle.load(f)
    with open("scaler.pkl", "rb") as f:
        scaler = pickle.load(f)
    with open("df_clean.pkl", "rb") as f:
        df = pickle.load(f)
    with open("rec_matrix.pkl", "rb") as f:
        rec_matrix = pickle.load(f)
    return model, knn, scaler, df, rec_matrix

model, knn, scaler, df, rec_matrix = load_assets()

# ── Label mappings ───────────────────────────────────────────
category_map = {v: k for k, v in enumerate(sorted(df["Category"].unique()))}
content_map  = {v: k for k, v in enumerate(sorted(df["Content Rating"].unique()))}
type_map     = {"Free": 0, "Paid": 1}

# ── UI ───────────────────────────────────────────────────────
st.title(" Mobile App Success Predictor & Recommender")
st.markdown("Fill in your app details below to predict its potential rating and discover competitors.")

st.divider()

# Input section
col1, col2 = st.columns(2)

with col1:
    category     = st.selectbox("App Category", sorted(df["Category"].unique()))
    content_rate = st.selectbox("Content Rating", sorted(df["Content Rating"].unique()))
    app_type     = st.radio("App Type", ["Free", "Paid"])

with col2:
    size    = st.slider("App Size (MB)", 1.0, 100.0, 20.0)
    price   = st.number_input("Price (USD)", min_value=0.0, max_value=400.0, value=0.0, step=0.99)
    reviews = st.number_input("Expected Reviews", min_value=0, max_value=10000000, value=1000, step=100)
    installs = st.selectbox("Expected Installs", [100, 1000, 10000, 100000, 1000000, 10000000])

st.divider()

# ── Predict button ───────────────────────────────────────────
if st.button(" Predict Rating & Find Similar Apps", use_container_width=True):

    # Encode inputs
    cat_encoded     = category_map.get(category, 0)
    content_encoded = content_map.get(content_rate, 0)
    type_encoded    = type_map.get(app_type, 0)

    # Build feature array
    input_features = np.array([[
        cat_encoded,
        content_encoded,
        type_encoded,
        size,
        price,
        installs,
        reviews
    ]])

    # Predict
    predicted_rating = model.predict(input_features)[0]
    predicted_rating = round(float(np.clip(predicted_rating, 1.0, 5.0)), 2)

    # ── Show prediction ──────────────────────────────────────
    st.subheader(" Prediction Result")

    if predicted_rating >= 4.0:
        st.success(f" Expected Rating: {predicted_rating} / 5.0 — Great potential!")
    elif predicted_rating >= 3.0:
        st.warning(f" Expected Rating: {predicted_rating} / 5.0 — Average potential.")
    else:
        st.error(f" Expected Rating: {predicted_rating} / 5.0 — Needs improvement.")

    # ── Recommendations ──────────────────────────────────────
    st.subheader(" Similar Apps You Might Compete With")

    # Build rec input
    rec_input  = scaler.transform([[cat_encoded, type_encoded, price]])
    distances, indices = knn.kneighbors(rec_input)

    similar_apps = df.iloc[indices[0][1:]][["App", "Category", "Rating", "Price", "Type"]].copy()
    similar_apps["Rating"] = similar_apps["Rating"].round(2)
    similar_apps.reset_index(drop=True, inplace=True)
    similar_apps.index += 1

    st.dataframe(similar_apps, use_container_width=True)

st.divider()
st.caption("Built with using Scikit-learn, XGBoost & Streamlit")
'''

with open("app.py", "w") as f:
    f.write(app_code)

print(" app.py written successfully!")